### PR TITLE
Change rgl.* to *3d

### PR DESCRIPTION
**Pull request by dmurdoch**
Some upcoming changes to the rgl package will require changes to
msir.  I will be deprecating a number of rgl.* function calls.
You can read about the issues here:

       https://dmurdoch.github.io/rgl/articles/deprecation.html

I have made the required changes to msir in the attached patch. These changes should work with both old and new rgl versions.

### CODE REVIEW

**Comment by luca-scr** [comment]
Hi Duncan, thanks for the commit. 
I'm checking if the proposed modifications produce exactly the same results and I have found some issues with the use of `rgl::surface3d()`.
In the previous code I had
```
rgl::rgl.surface(xgrid, zgrid, pred,  ...)
```
and you propose to use
```
rgl::rgl.surface(x = xgrid, z = zgrid, y = pred,  ...)
```
but this produces an error
```
Error in rgl.surface(x = c(-1, -0.916666666666667, -0.833333333333333,  : 
  Bad dimension for cols
```
I was able to avoid the error by using
```
rgl::surface3d(x = xgrid, y = zgrid, z = pred, ...)
```
but the resulting (2D smooth) surface is not the same as with the original code. 
Looking at `rgl::surface3d()` it seems that it is using `coords = c(1, 3, 2)` while the original code using `rgl::rgl.surface()` had the default `coords = 1:3`.

**Comment by dmurdoch** [comment]
Sorry about that.  That's a bug in surface3d that has been fixed, but my 
first fix (the one on CRAN) was incomplete.  So if you are not using the 
latest rgl (0.111.6), you should update to that.  But it might not work, 
and you'll need to wait for the upcoming release, or install the devel 
version of rgl from Github.

Duncan Murdoch

**Comment by luca-scr** [comment]
Ok, I'll wait the updated release to appear on CRAN.

**Comment by dmurdoch** [comment]
That's the simplest solution.  It is possible to do get the version you've got to display like rgl.surface, but it's not worth the trouble, when the other fix is coming soon.

**Comment by dmurdoch** [comment]
I just took another look at this, and in the example I tried, spinplot works with both CRAN and devel versions of rgl.  I did make the change to argument order that you made, and I'm not seeing a difference in the output.  Could you show me the code that generates the different output?

**Comment by luca-scr** [comment]
Using the current CRAN version of **rgl** and this code
```
library(msir)
x1 <- rnorm(100)
x2 <- rnorm(100)
y  <- 2*x1 + x2^2 + 0.5*rnorm(100)
spinplot(x1, y, x2, fit.smooth = TRUE)
```

This a view of obtained using `rgl::rgl.surface(x = xgrid, z = zgrid, y = pred, ...)`

rgl_surface

and this is the same view (approx) obtained using `rgl::surface3d(x = xgrid, y = zgrid, z = pred, ...)`

surface3d

**Pull request merged**
